### ISSUE TITLE
[FEATURE] Add jobStartTime for in state

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#123]
* add jobStartTime into
  * IndexStateDoc.
  * SessionDoc.
* jobStartTime is immutable.

**Comment by dai-chen** [comment]
1. Add `jobStartTime` in metadata log entry only when trigger the auto refresh (won't touch this when update heartbeat)
2. Add missing `latestId` in metadata log entry
3. Make timer thread pool singleton and shutdown it in FlintRepl main
4. Change createIndex() to allow transit from DELETED and maybe CREATING state
5. Remove old EMR info stored in Flint metadata
