### ISSUE TITLE
[BUG] CODEOWNERS is out of sync

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-spark#15]
**What is the bug?**

CODEOWNERS should match MAINTAINERS

**Do you have any additional context?**

Caught by some automation. Create a CODEOWNERS file with the list of maintainer aliases please.

**Comment by penghuo** [comment]
I add in here. https://github.com/opensearch-project/opensearch-spark/blob/main/.github/CODEWONERS. is it correct?

**Comment by penghuo** [comment]
i see, typo in name, right?
