### ISSUE TITLE
Remove 2s delay between result write and statement state update

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/opensearch-spark#180]
As https://github.com/opensearch-project/sql/issues/2436 fixed in PPL plugin, the previous mitigation (2 seconds sleep between result index write and statement state update) can be removed.

Ref: https://github.com/opensearch-project/opensearch-spark/pull/174

**Comment by dai-chen** [comment]
For the safe side, this will be fixed after the fix in PPL plugin rollout.

**Comment by kaituo** [comment]
fixed in https://github.com/opensearch-project/opensearch-spark/pull/245
