### ISSUE TITLE
[FEATURE] Index refresh job management phase 2

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/opensearch-spark#190]
**Is your feature request related to a problem?**

In Flint 0.1, https://github.com/opensearch-project/opensearch-spark/issues/57 added `RECOVER INDEX JOB` statement for index refresh job restart. There are other useful management statements still missing, such as show index refresh status and progress, stop index auto refresh etc.

**What solution would you like?**

1. `SHOW INDEX JOB` statement shows job info that may include:
    a. Job status (refreshing or terminated)
    b. Progress (how many files are refreshed)
    c. Last update time (heartbeat timestamp)
2. `CANCEL INDEX JOB` statement terminates the refresh job (index data will be stale later). Example use includes:
    a. Current index data is sufficient for user;
    b. Gracefully stop the refresh job before internal deployment

**Comment by seankao-az** [comment]
## Index job management: SHOW statement
Show detailed info for all Flint indexes, including non auto refresh indexes.

1. `SHOW INDEX [JOB|JOBS] ON table_name` : list all index jobs on a table
2. `SHOW INDEX [JOB|JOBS] IN catalog[.database]` : list all index jobs in a catalog (or database)

These statements should return information on:
* index name (job name)
* database
* source table name
* index kind
* properties
  * auto refresh setting
  * refresh interval setting
  * incremental refresh setting
  * checkpoint location setting
* job status (active, refreshing, deleting, deleted, failed, recovering, vacuuming, etc.)
* last update time (last heartbeat time or last refresh time?)
```
SHOW INDEX JOBS

Flint job name | database | source table | kind | properties | job status | last update time
--------------------------------------------------------------------------------------
flint_spark... | default | http_logs | skipping | {"auto_refresh": false, ...} | active | 1708603322
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | refreshing | 1708624771
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | paused | 1708624771

SHOW INDEX JOBS ON alb_logs

Flint job name | database | source table | kind | properties | job status | last updated time
--------------------------------------------------------------------------------------
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | refreshing | 1708624771
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | paused | 1708624771

SHOW INDEX JOBS IN glue_1

Flint job name | database | source table | kind | properties | job status | last updated time
--------------------------------------------------------------------------------------
flint_spark... | default | http_logs | skipping | {"auto_refresh": false, ...} | active | 1708603322
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | refreshing | 1708624771
flint_spark... | default | alb_logs | covering | {"auto_refresh": true, ...} | paused | 1708624771
flint_spark... | other | http_logs | skipping | {"auto_refresh": false, ...} | active | 1708603322
```

**Comment by seankao-az** [comment]
To find indices, reference:
* [list covering index for a table](https://github.com/opensearch-project/opensearch-spark/blob/faa0d0769dc0c03b51e1d51150a21ed59e02e2c5/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala#L76-L79)
* [list materialized views for catalog / database](https://github.com/opensearch-project/opensearch-spark/blob/faa0d0769dc0c03b51e1d51150a21ed59e02e2c5/flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala#L73-L76)

Find all indexes for table: `flintIndexNamePrefix(fullTableName) + "_*"`
Find all indexes for catalog / database: `"flint_${catalogDbName}_*"`

**Comment by seankao-az** [comment]
To get index job details
* Some fields are available in FlintMetadata:
  * name
  * kind
  * source `catalog.database.table`
      * catalog
      * database
      * table
  * options
      * auto_refresh
      * refresh_interval
      * incremental_refresh
      * checkpoint_location
* For job status and last update time, check Flint metadata log
  * entries with type "flintindexstate"
  * entry for each index has a [static id](https://github.com/opensearch-project/opensearch-spark/blob/faa0d0769dc0c03b51e1d51150a21ed59e02e2c5/flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java#L57)

TODO: understand how job status is updated and whether last update time in metadata log == index last refreshed time

**Comment by dai-chen** [comment]
The requirements here is partially met in the following work:

1. https://github.com/opensearch-project/opensearch-spark/issues/265: Show Flint index statement display both index metadata and state
2. https://github.com/opensearch-project/opensearch-spark/issues/278: Alter index statement makes more sense than cancel, otherwise auto refresh index semantic is violated

Closing and reopen in future as needed.
