### ISSUE TITLE
[FEATURE] Using PIT search vs Scroll search

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#246]
**Is your feature request related to a problem?**
* In case OpenSearch serverless does not support scroll search, It will also impact REPL search query request from query_request_index.

**What solution would you like?**
* Using PIT search for data index access.
* REPL search query request from query_request_index without using scroll search.

**What alternatives have you considered?**
n/a

**Do you have any additional context?**

**Comment by kaituo** [comment]
changed to "REPL search query request from query_request_index without using scroll search."
