### ISSUE TITLE
[FEATURE] Show Flint indexes support

### ISSUE THREAD

**Issue by seankao-az** [opensearch-project/opensearch-spark#265]
**Is your feature request related to a problem?**
1. Getting a list of all Flint indexes takes too long.
Currently, user needs to make request to show all databases, show all tables, and then get all the indexes from the databases and tables.
2. Cannot get Flint index names right away.
Users need to be aware of the Flint index naming rule and construct the name themselves, using datasource, database, table, index type, and index name.

**What solution would you like?**
provide a query for showing all the flint indexes with their info, including the internal index state.
`SHOW FLINT [INDEX|INDEXES] IN catalog[.database]`

```
SHOW FLINT INDEXES IN glue_1

flint_index_name | kind | database | table | index_name | auto refresh  | status
--------------------------------------------------------------------------------
flint_glue_1_default_http_logs_cv_index | covering | default | http_logs | cv | true | active
flint_glue_1_other_http_logs_skipping_index | skipping | other| http_logs | - | true | refreshing
flint_glue_1_other_http_count_view | mv | other| - | http_count_view | false | active
```

**What alternatives have you considered?**
1. `SHOW FLINT [INDEX|INDEXES]`
Compared to the proposed solution, the intention for this statement is more unclear. It's not clear whether this statement should fetch all indexes in all catalogs or in current catalog only

2. Debated on whether to add FLINT as a keyword.
`SHOW INDEXES` or `SHOW ALL INDEXES` can be confused with the already existing `SHOW INDEXES ON <table>` statement for showing covering indexes, thus adding `FLINT` to make the distinction. In addition, this statement does not return the index name provided by user, but the Flint index name stored in OpenSearch, so that lines up as well.

**Do you have any additional context?**

**Comment by dai-chen** [comment]
This can be closed now?
