### ISSUE TITLE
[META] Bucket of Improvements to the Spark Integration for 2.13

### ISSUE THREAD

**Issue by brijos** [opensearch-project/opensearch-spark#277]
**Is your feature request related to a problem?**
We released our Spark integration starting in 2.9 with skipping index support and have received feedback that we need to focus on making it easier for customers to connect to their data in object stores. In 2.13, we will improve the admin UX in Data Sources by reinforcing [OpenSearch Integrations](https://playground.opensearch.org/app/integrations#/available) as the out-of-the-box way to easily connect to your data using Hive, Spark, and your object store. We'll also make it easier for customers to [create](https://github.com/opensearch-project/opensearch-spark/issues/221) manage accelerations from within data sources and include [Bloom Filters for high cardinality skipping indexes](https://github.com/opensearch-project/opensearch-spark/issues/206) such as hostnames and IP addresses. For querying, we will include better error reporting and will extend JOIN functionality to PPL.

Below is a comprehensive view of what other optimizations and bugs will be addressed in 2.13:

Features
[Exclude logical deleted Flint index from query rewrite](https://github.com/opensearch-project/opensearch-spark/issues/272)
[Show Flint indexes support](https://github.com/opensearch-project/opensearch-spark/issues/265)
[Creating an index fails with OpenSearch Carbon domain, and the error message is not meaningful](https://github.com/opensearch-project/opensearch-spark/issues/252)
[Standardize Flint log output format](https://github.com/opensearch-project/opensearch-spark/issues/235)
[Avoid expensive S3 listing by using file list in skipping index](https://github.com/opensearch-project/opensearch-spark/issues/218)
[Checkpoint folder data cleanup limitation](https://github.com/opensearch-project/opensearch-spark/issues/102)
[Skipping index and materialized view refresh synchronization](https://github.com/opensearch-project/opensearch-spark/issues/93)
[Large backlog processing when materialized view cold start](https://github.com/opensearch-project/opensearch-spark/issues/90)
[Support partial indexing for skipping and covering index](https://github.com/opensearch-project/opensearch-spark/issues/89)
[Covering index and materialized view refresh idempotency](https://github.com/opensearch-project/opensearch-spark/issues/88)
[Improve validation for SQL statement](https://github.com/opensearch-project/opensearch-spark/issues/65)
[Add stateCode if job executed failed](https://github.com/opensearch-project/opensearch-spark/issues/149)

Bugs
[Stop Spark context and JVM explicitly in FlintJob](https://github.com/opensearch-project/opensearch-spark/issues/270)
[Manual cancel REPL session in EMR-S console, Shutting down hock does not update state](https://github.com/opensearch-project/opensearch-spark/issues/269)
[Create MV should expose error message properly](https://github.com/opensearch-project/opensearch-spark/issues/264)
[Flint index stuck in transient state](https://github.com/opensearch-project/opensearch-spark/issues/249)
[Gracefully terminate index refresh job when Flint index deleted accidentally](https://github.com/opensearch-project/opensearch-spark/issues/244)
[Flint data source cannot read nested field value](https://github.com/opensearch-project/opensearch-spark/issues/233)
[Remove unnecessary locking when commit and rollback transaction](https://github.com/opensearch-project/opensearch-spark/issues/226)
[If user provide invalid s3 location as checkpoint, streaming query still execute, but using local disk as checkpoint](https://github.com/opensearch-project/opensearch-spark/issues/200)
[Remove 2s delay between result write and statement state update](https://github.com/opensearch-project/opensearch-spark/issues/180)
[Missing errors when connecting to a Parquet table with incorrect types](https://github.com/opensearch-project/opensearch-spark/issues/101)
[Find correct catalog name in query rewriter](https://github.com/opensearch-project/opensearch-spark/issues/54)
[Field with null value is omitted when write back to result index](https://github.com/opensearch-project/opensearch-spark/issues/139)
[Flint not supporting Complex schema](https://github.com/opensearch-project/opensearch-spark/issues/112)

Improve Error Reporting
[Error message is not meaning full, "Fail to run query, cause: Failed to refresh Flint index"](https://github.com/opensearch-project/opensearch-spark/issues/201)

**Comment by brijos** [comment]
Items slated for release are within the following queries:

https://github.com/opensearch-project/opensearch-spark/releases/tag/v0.2.0
https://github.com/opensearch-project/opensearch-spark/issues?q=+is%3Aissue+label%3A0.3

**Comment by anirudha** [comment]
move major 2.13 items to release/ we need to rebucket the low hanging items here
