### ISSUE TITLE
[FEATURE]Support complex predicates for IF function in PPL

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#398]
### Description
The predicate of function `if(predicate, arg1, arg2)` in PPL should support complex expression.
The current implementation only supports `TrueLiteral` and `FalseLiteral`, just like the example given in [doc](https://github.com/opensearch-project/sql/blob/7b40c2c6a1a83329a0805cb367a8a56f9fbe2c4b/docs/user/ppl/functions/condition.rst#if). Query such as `|eval test=if(pgs > 2, "yes", "no")` will fail with `"details": "Failed to parse query due to offending symbol [>] at:` 
 
This PR aims to support complex predicate expression, following cases will be supported:
- if(a > 2,  arg1, arg2)
- if(a != 2,  arg1, arg2)
- if(isnull(a),  arg1, arg2)
- if(not a>2,  arg1, arg2)
- if(not a in (0, 1), arg1, arg2)"
- if(not a in (0, 1) OR isnull(a), arg1, arg2)
- if(like(a, '_a%b%c_d_'), arg1, arg2)
- and more

### Issues Resolved
Resolves https://github.com/opensearch-project/sql/issues/2600 and https://github.com/opensearch-project/sql/issues/2653
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### Additional Context
https://github.com/opensearch-project/sql/pull/2756

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta)]

**Comment by YANG-DB** [comment]
This is replaced with [CASE](https://github.com/opensearch-project/opensearch-spark/issues/645) functionality
