### ISSUE TITLE
[FEATURE]Add `eval` PPL command

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#429]
**Is your feature request related to a problem?**
Add `eval` command for PPL spark based execution driver

- [PPL eval command](https://github.com/opensearch-project/sql/blob/d3ecb2d75712db2bcbd2945e62728c6599580657/docs/user/ppl/cmd/eval.rst)

**Do you have any additional context?**
 - https://github.com/opensearch-project/sql/blob/d3ecb2d75712db2bcbd2945e62728c6599580657/docs/user/ppl/cmd/eval.rst
 - https://github.com/opensearch-project/opensearch-spark/issues/408

**Comment by LantaoJin** [comment]
I am working on this.
