### ISSUE TITLE
[Refactor] Add more tests for PPL queries

### ISSUE THREAD

**Issue by ykmr1224** [opensearch-project/opensearch-spark#446]
**Is your feature request related to a problem?**
Tests for PPL query does not contain enough to cover all the supported syntax and edge cases.

**What solution would you like?**
Add more tests for PPL query to cover more syntax and edge cases. We might want to refer [integ-test in SQL plugin](https://github.com/opensearch-project/sql/tree/main/integ-test/src/test/java/org/opensearch/sql/ppl) for the test cases.

**What alternatives have you considered?**
Possible solution could be having same set of test cases for spark and SQL plugin, but it could be overkill.

**Do you have any additional context?**
This is raised during discussing about PPL gaps between spark and SQL plugin among @YANG-DB, @seankao-az, @ykmr1224, @anasalkouz

**Comment by YANG-DB** [comment]
this was addressed in the recent code refectories
