### ISSUE TITLE
[FEATURE] add `Rare` PPL command

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#461]
Add PPL `rare` command described [here](https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/ppl/cmd/rare.rst)

**Do you have any additional context?**
 - https://github.com/opensearch-project/opensearch-spark/issues/408

**Comment by YANG-DB** [comment]
@noCharger please add the original PPL command here as context

**Comment by LantaoJin** [comment]
Design Doc
-

Similar to https://github.com/opensearch-project/opensearch-spark/issues/536.

### Syntax
```
rare <field-list> [by <by-field-list>]
```


`rare` results maximum 10 distinct least frequent values for a specified field list grouped by the group-by fields.
It equals to
```
source = t | stats count(1) as count by <field-list>+<by-field-list> | sort count | fields  <field-list> | head 10
```

So the Spark Logical Plan should be
```
Limit 10
+- Sort [count ASC NULLS FIRST]
   +- Aggregate [<field-list>+<by-field-list>], [count(1) AS count]
      +- ...
         +- UnresolvedRelation
```
