### ISSUE TITLE
Add PPL `Patterns` command

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#462]
Add patterns command using the next [OpenSearch PPL functionality](https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/ppl/cmd/patterns.rst)

**Do you have any additional context?**
 - https://github.com/opensearch-project/opensearch-spark/issues/408

**Comment by YANG-DB** [comment]
@noCharger please add the original PPL command here as context
