### ISSUE TITLE
Missing PPL command - Interval

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#463]

**Comment by YANG-DB** [comment]
@noCharger can you please add the original PPL command here ? additional context is needed
Maybe its is related to the [`adddate` command ?](https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/dql/functions.rst#adddate)

**Comment by dblock** [comment]
Let's close until there's a proper description

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/reta)]
