### ISSUE TITLE
[FEATURE] Add `distinct_count` PPL command

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/opensearch-spark#484]
This is part of the `stats` command with specific

**Comment by salyh** [comment]
See https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/ppl/cmd/stats.rst#example-7-calculate-the-distinct-count-of-a-field

**Comment by salyh** [comment]
It seems that the distinct_count stats function is already implemented but a) with bugs and b) without tests

I fixed the bugs and add a integ test:
https://github.com/eliatra/opensearch-spark/commit/2ef5890a4c9bf881fdfab382e3af5f0c681ddcdf

Not sure if i missed something but that makes it working for me.

cc @YANG-DB @anasalkouz If the code looks good for you, I am happy to open a PR

**Comment by YANG-DB** [comment]
thanks @salyh 
yes, please create a PR ...
