### ISSUE TITLE
[FEATURE]Add `isEmpty` ppl command

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#512]
**Is your feature request related to a problem?**
Add `isEmpty` command for PPL spark based execution driver .

Since spark sql doesnt offer such expression a possible option would be:
-  translate the expression into a where clause which is an equivalent of 
```
SELECT CASE  
       WHEN length(trim(column_name)) = 0 THEN true 
        ELSE false     
END AS is_empty
```
-  register a custom expression `IsEmptyExpression`

**Do you have any additional context?**
 - https://github.com/opensearch-project/opensearch-spark/issues/408

**Comment by kt-eliatra** [comment]
@YANG-DB 
hi, just to confirm, `isempty` as well as [ispresent](https://github.com/opensearch-project/opensearch-spark/issues/518) and  [isblank](https://github.com/opensearch-project/opensearch-spark/issues/513) - all of them should be implemented as a commands?
e.g `source=table | isempty(column);`
Or rather as a functions? e.g. `source=table | fields col_a, col_b | where isempty(col_c)`?

**Comment by YANG-DB** [comment]
IMO functions - @LantaoJin what are your thoughts?

**Comment by lukasz-soszynski-eliatra** [comment]
@YANG-DB 
I have a question related to the edge case associated with ternary logic. What should be the outcome of invoking `eval r = isempty(null)`?  According to the below definition
```sql
SELECT CASE  
       WHEN length(trim(column_name)) = 0 THEN true 
        ELSE false     
END AS is_empty
```
`isempty(null)` evaluates to `true`. Is this expected?

**Comment by salyh** [comment]
can we close this as https://github.com/opensearch-project/opensearch-spark/pull/676 is merged?
