### ISSUE TITLE
[FEATURE]Add `ispresent` PPL command

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#518]
**Is your feature request related to a problem?**
Add `ispresent` command for PPL spark based execution driver .

Since spark sql doesnt offer such expression a possible option would be:
-  use `WHERE` spark sql command
```
    WHERE  "column_name" IS NOT NULL
```
-  register a custom expression `ispresent`

**Do you have any additional context?**

 - https://github.com/opensearch-project/opensearch-spark/issues/408

**Comment by lukasz-soszynski-eliatra** [comment]
`ispresent` implemented as a function. @YANG-DB the MR is ready for review.

Example: `search source=people | eval p=ispresent(age) | where ispresent(age);`
