### ISSUE TITLE
[FEATURE]Add PPL Explain Command / Endpoint

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#556]
**Is your feature request related to a problem?**
In a similar way that OpenSearch PPL can create a query with `explain` flag that will produce the execution plan / actual query that is being run against the server, Spark PPL needs a matching capability

**What solution would you like?**
Create an `explain` flag attribute that will respond with the logical / execution plan for the given query.

**Do you have any additional context?**
- https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/interfaces/endpoint.rst#explain

**Comment by kt-eliatra** [comment]
@YANG-DB 

I prepared a working prototype https://github.com/opensearch-project/opensearch-spark/commit/ae687d6c0f939fab86208e03bb016d4a18acb497

 If it looks good for you I'll prepare a PR

**Comment by YANG-DB** [comment]
Nice - please add that to the comments of the issue itself and we can discuss it further...
In addition I would add a `|` after the 'explain' command and remove the '=true ' ...
