### ISSUE TITLE
[BUG] Eval function doesn't work in PPL

### ISSUE THREAD

**Issue by A-Gray-Cat** [opensearch-project/opensearch-spark#559]
**What is the bug?**
'eval' function doesn't work in PPL

**How can one reproduce the bug?**
1. Go to Data sources -> securitylake -> query data -> open log explorer
2. Run the follow queries:
```
source = securitylake.amazon_security_lake_glue_db_us_east_1.amazon_security_lake_table_us_east_1_cloud_trail_mgmt_2_0 | eval t = 2 + 2 
| fields t 
| where time_dt > '2024-08-11 00:00:00' and region = 'us-east-1' 
| head 10
```
and you will get `{"Message":"Fail to run query. Cause: Not Supported operation : Eval"}`

**What is the expected behavior?**
`eval` function works as expected

**What is your host/environment?**
 - Version 2.13
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by YANG-DB** [comment]
This issue was resolved [here](https://github.com/opensearch-project/opensearch-spark/issues/429)
