### ISSUE TITLE
[FEATURE] Dynamically adjust rate limit for OpenSearch requests

### ISSUE THREAD

**Issue by ykmr1224** [opensearch-project/opensearch-spark#570]
**Is your feature request related to a problem?**
When creating/updating index into OpenSearch, it could cause throttling due to too much request.
Although rate limit is implemented (https://github.com/opensearch-project/opensearch-spark/pull/567), as it uses Spark parameter, we cannot adjust the limit once the streaming job is started.

**What solution would you like?**
We want to come up with a way to dynamically adjust rate limit so that user can modify late limit even after they started a job.

**What alternatives have you considered?**
Alter the index to manual refresh, and change back to auto refresh, which would start new streaming job, and can pick up new rate limit config.

**Do you have any additional context?**
n/a

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/reta), [5](https://github.com/cwperks)]

**Comment by ykmr1224** [comment]
Replaced with https://github.com/opensearch-project/opensearch-spark/issues/640
