### ISSUE TITLE
[FEATURE] VACCUM index statement should delete checkpoint data

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#580]
**Is your feature request related to a problem?**

A follow up of https://github.com/opensearch-project/opensearch-spark/issues/104 - VACCUM index statement which deletes both index data and checkpoint data (if any), currently VACCUM will only delete the index itself

**Comment by dai-chen** [comment]
Related to https://github.com/opensearch-project/opensearch-spark/issues/102.
