### ISSUE TITLE
[REFACTOR] Unify the async query request metadata model

### ISSUE THREAD

**Issue by ykmr1224** [opensearch-project/opensearch-spark#602]
**Is your feature request related to a problem?**
Currently in async-query-core, we have three models which store the async query request and status: AsyncQueryJobMetadata, StatementModel, and IndexDMLResult. And those are stored in the same request index (`.query_request_index_{datasourceName}`) with different documentId (`qid{requestId}`, `{requestId}`, `index{requestId}`).
These three models overwraps each other and redundant. It also causes confusion.

**What solution would you like?**
Unify them to single model, and store single record in request index.

I propose following unified model to be used:

## AsyncQueryMetadata

- queryId (PK)
- query // from StatementModel
- langType // from StatementModel
- datasourceName
- accountId
- jobType
- submitTime
- sessionId
- indexName
- state // from StatementModel/IndexDMLResult
- error // from StatementModel/IndexDMLResult
- queryRunTime
- applicationId
- jobId
- version (= "2.0")
- resultIndex
- statementId (= queryId) // from StatementModel

### How to make it backward compatible?
In new version, we will use single interface to query/save the query metadata.
The documentId will be queryId (without prefix).
Since current StatementModel uses queryId as a key, use case for StatementModel would be fine (whether it hits older record or newer record, it contains required fields for statement use case).
For the use case for AsyncQueryMetadata (It is only when GetAsyncQueryResults API is called), we can first query with queryId (without prefix), and if the version field is not "2.0", fallback to query with "qid" prefix, which would retrieve AsyncQueryJobMetadata(older) record.
IndexDMLResult does not have read use case. (does not have concern on backward compatibility)

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by noCharger** [comment]
most of the fields here already defined in https://github.com/opensearch-project/sql/blob/main/async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java#L22-L35

for spark side, can we just reuse https://github.com/opensearch-project/opensearch-spark/blob/main/flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala

**Comment by ykmr1224** [comment]
> most of the fields here already defined in https://github.com/opensearch-project/sql/blob/main/async-query-core/src/main/java/org/opensearch/sql/spark/execution/statement/StatementModel.java#L22-L35
> 
> for spark side, can we just reuse https://github.com/opensearch-project/opensearch-spark/blob/main/flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala

Yes, I think we can reuse, but we might want to align the model name to reduce confusion.
