### ISSUE TITLE
[WIP][FEATURE] Heartbeat on query execution

### ISSUE THREAD

**Issue by noCharger** [opensearch-project/opensearch-spark#617]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is, e.g. _I'm always frustrated when [...]_

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by andrross** [comment]
[Catch All Triage - [1](https://github.com/AmiStrn), [2](https://github.com/mch2), [3](https://github.com/andrross)]

@noCharger Please provide more detail if you're working on this feature.
