### ISSUE TITLE
[FEATURE]New `fieldsummary` PPL command

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#662]
**Describe the solution you'd like**
We propose adding a new `fieldsummary` command to OpenSearch PPL that would provide summary statistics for all fields in the current result set. 

_This command should:_

1. Calculate basic statistics for each field (count, distinct count, min, max, avg for numeric fields)
2. Determine the data type of each field
3. Show the most frequent values and their counts for each field
4. Calculate the percentage of events that contain each field

Additionally, the command should support the following key optional parameters:

1. _**includefields**:_
Specify which fields to include in the summary (e.g., `| fieldsummary includefields="status_code,user_id,response_time"`)
3. _**excludefields**:_ 
Specify which fields to exclude from the summary (e.g., `| fieldsummary excludefields="internal_id,debug_info"`)
4. _**topvalues**:_ 
Set the number of top values to display for each field (e.g., `| fieldsummary topvalues=5`)
5. _**maxfields**:_ 
Limit the number of fields to display (e.g., ` | fieldsummary maxfields=20`)
6. _**nulls**:_ 
Include null/empty value counts (e.g., `| fieldsummary nulls=true`)

**Example usage:**

```sql
source = t
| where timestamp >= "2023-01-01" and timestamp < "2023-02-01"
| fieldsummary includefields="status_code,user_id,response_time" topvalues=3 nulls=true
```

This command would generate a table with summary statistics for the specified fields in the given date range, showing the top 3 values for each field and including null counts.

**Example output:**

| Field         | Count | Distinct | Min  | Max  | Avg  | Type   | Top Values                                                        | Nulls |
|---------------|-------|----------|------|------|------|--------|-------------------------------------------------------------------|-------|
| status_code   | 10000 | 4        | 200  | 503  | -    | short  | 200 <br>404 <br>500              | 0     |
| user_id       | 9500  | 1200     | -    | -    | -    | string | user123 <br>user456<br>user789      | 500   |
| response_time | 10000 | 986      | 0.01 | 10.5 | 0.75 | float  | 0.5<br>0.75<br>1.0           | 0     |

**Comment by YANG-DB** [comment]
Given the above specifications, the pushed-down query to generate a `fieldsummary` should take the next form:
```sql
WITH field_summary AS (
    SELECT
        COUNT(*) AS total_count,
        COUNT(column_name) AS count_non_null, 
        COUNT(DISTINCT column_name) AS distinct_count,
        MIN(column_name) AS min_value,
        MAX(column_name) AS max_value,
        AVG(CAST(column_name AS DOUBLE)) AS avg_value,
        COLLECT_LIST(STRUCT(column_name, COUNT(column_name))) AS top_values
    FROM table_name
    WHERE timestamp >= "2023-01-01" 
      AND timestamp < "2023-02-01"
    GROUP BY column_name
)
SELECT
    column_name AS Field,
    count_non_null AS Count,
    distinct_count AS Distinct,
    min_value AS Min,
    max_value AS Max,
    avg_value AS Avg,
    CASE 
        WHEN typeof(column_name) = 'integer' THEN 'int'
        WHEN typeof(column_name) = 'float' THEN 'float'
        ELSE 'string'
    END AS Type,
    top_values,
    total_count - count_non_null AS Nulls
FROM field_summary
ORDER BY total_count DESC
LIMIT 20;
```

where for each column name we will produce such a summary query

**Comment by YANG-DB** [comment]
@LantaoJin I would appreciate u'r feedback here since I suspect this type of query may cause a significant compute - any best practices recommended ?

**Comment by LantaoJin** [comment]
@YANG-DB I think we don't need to do this rewriting. Spark itself contains a similar API call `Dataset.describe`, you can refer https://github.com/apache/spark/blob/master/sql/api/src/main/scala/org/apache/spark/sql/api/Dataset.scala#L2486 to build a new implementation. Or more specific, try https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/stat/StatFunctions.scala

Here is an example:
```scala
val sourceData = Seq(
      (1, "1066", "Failed password", "Engineering"),
      (2, "1815", "Failed password", "IT"),
      (3, "1916", "Session closed", null), // Changed to null for testing
      (4, null, "Failed password", null), // Changed to null for testing
      (5, "1690", "Session closed", "Engineering"),
      (6, "1090", "Session closed", "Engineering")
    ).toDF("id", "uid", "action", "department")

sourceData.describe("id", "uid", "action", "department").show
```

The output is 
```
+-------+------------------+------------------+---------------+-----------+
|summary|                id|               uid|         action| department|
+-------+------------------+------------------+---------------+-----------+
|  count|                 6|                 5|              6|          4|
|   mean|               3.5|            1515.4|           NULL|       NULL|
| stddev|1.8708286933869707|407.32394970097204|           NULL|       NULL|
|    min|                 1|              1066|Failed password|Engineering|
|    max|                 6|              1916| Session closed|         IT|
+-------+------------------+------------------+---------------+-----------+
```
