### ISSUE TITLE
[FEATURE]Add `flatten` Command to PPL

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#669]
**Is your feature request related to a problem?**
OpenSearch Piped Processing Language (PPL) currently lacks a native command to flatten nested objects or arrays in documents. Many datasets, especially those containing JSON objects, have deeply nested fields that are difficult to work with in their raw form. The `flatten` command will simplify these structures and make it easier to analyze and extract data.

**What solution would you like?**
Introduce a flatten command in PPL that can handle arrays or nested fields, producing a `flattened` result that contains all the nested elements at the top level.

**Syntax:**
```sql
source=<data_source> | flatten <nested_field>  | fields <fields_to_select>
```
 - The `flatten` command takes a nested array or object field and returns each element as part of a flat structure.

---

**Example Use Cases**

1. Flattening an Array Field

```sql
source=my-index  | flatten bridges | fields _time, bridges, city, country
```
This query `flattens` the bridges array field.

_Example Input:_

```json
{
  "_time": "2024-09-13T12:00:00",
  "bridges": [
    {"name": "Tower Bridge", "length": 801},
    {"name": "London Bridge", "length": 928}
  ],
  "city": "London",
  "country": "England"
}
```

_Expected Output:_

```json
[
  {
    "_time": "2024-09-13T12:00:00",
    "name": "Tower Bridge",
    "length": 801,
    "city": "London",
    "country": "England"
  },
  {
    "_time": "2024-09-13T12:00:00",
    "name": "London Bridge",
    "length": 928,
    "city": "London",
    "country": "England"
  }
]
```

2. Flattening a Nested Object

```sql
source=my-index | flatten details | fields _time, details 
```

This query `flattens` the details object field.

_Example Input:_

```json
{
  "_time": "2024-09-13T12:00:00",
  "details": {
    "name": "Alice",
    "age": 30,
    "address": {
      "street": "Main St",
      "city": "New York"
    }
  }
}
```

_Expected Output:_

```json
{
  "_time": "2024-09-13T12:00:00",
  "name": "Alice",
  "age": 30,
  "street": "Main St",
  "city": "New York"
}
```

---

**Additional Considerations**

- The flatten command should work efficiently with large arrays or deeply nested structures.
- It must handle complex JSON objects where multiple levels of nesting exist.
 - Consider supporting multi-level flattening for more deeply nested fields (e.g., flatten details.address).

**Comment by vamsi-amazon** [comment]
Shouldn't it be bridges.name in flattened object? 
|What if multiple object fields has same key inside them?

**Comment by salyh** [comment]
> Shouldn't it be bridges.name in flattened object? |What if multiple object fields has same key inside them?

Asmentioned above "Consider supporting multi-level flattening for more deeply nested fields (e.g., flatten details.address)." I read it as: yes, we support it. Question is what is the default and should it be configurable?

**Comment by salyh** [comment]
@YANG-DB @vamsi-amazon 

cc @dr-lilienthal

Before opening a PR, a few design questions and requirement refinements need to be discussed.

1) Does the terms `nested objects or arrays` and `nested_field` refer to a) the datatype "Nested Field" in OpenSearch like described [here](https://opensearch.org/docs/latest/field-types/supported-field-types/nested/#nested-field-type-1) OR does the terms refer to to b) just a field in a json document which value is a another json array or object? In the first case its relevant to point out that the OpenSearch  "Nested Field" datatype is only for arrays and not objects. So the assumption is that b) applies

2) If above b) applies then it appears that nested arrays in OpenSearch are always "NULL" when queried via Spark SQL or Spark PPL. Nested objects however can be queried as expected. This is possibly a bug and needs to be adressed first before this issue can be solved.

3) It would help to add the expected input and output in a table structure to the examples because its not yet clear if the flattened object should be added as separate fields to the datarow.

**Comment by YANG-DB** [comment]
@salyh 
1) IMO a general nested field (not specifically opensearch mapping)
2) yes, we need to solve this specific OpenSearch PPL issue separately 
3) Examples:

```sql
source=employees 
| flatten contact 
| fields name, age, contact.phone as phone, contact.address.city as city, contact.address.zipcode as zipcode

```
results using alias:

| Name  | Age | Phone      | City      | Zipcode |
|-------|-----|------------|-----------|---------|
| Alice | 30  | 123-4567   | New York  | 10001   |
| Alice | 30  | 789-0123   | New York  | 10001   |
| Bob   | 25  | 234-5678   | Los Angeles | 90001   |
| Bob   | 25  | 890-1234   | Los Angeles | 90001   |

```sql
source=employees 
| flatten contact 
| fields name, age, contact.phone, contact.address.city, contact.address.zipcode
```

results:
| Name  | Age | contact.phone | contact.address.city | contact.address.zipcode |
|-------|-----|----------------|----------------------|-------------------------|
| Alice | 30  | 123-4567       | New York             | 10001                   |
| Alice | 30  | 789-0123       | New York             | 10001                   |
| Bob   | 25  | 234-5678       | Los Angeles          | 90001                   |
| Bob   | 25  | 890-1234       | Los Angeles          | 90001                   |

4) IMO we can merge both - lets discuss this more

**Comment by lukasz-soszynski-eliatra** [comment]
I indexed a few documents like the below one in OpenSearch
```json
	"hits": [
			{
				"_index": "bridges",
				"_id": "hn_qcZIBFrW1jO9hyGc5",
				"_score": 1.0,
				"_source": {
					"_time": "2024-09-13T12:00:00",
					"bridges": [
						{
							"name": "Tower Bridge",
							"length": 801
						},
						{
							"name": "London Bridge",
							"length": 928
						}
					],
					"city": "London",
					"country": "England"
				}
			},
```
When I query the table via Spark SQL, I receive
```sql
select * from dev.default.bridges;
country	city	bridges	_time
England	London	NULL	2024-09-13 12:00:00
England	London	NULL	2024-09-13 12:00:00
France	Paris	NULL	2024-09-13 12:00:00
Italy	Venice	NULL	2024-09-13 12:00:00
Czech Republic	Prague	NULL	2024-09-13 12:00:00
Hungary	Budapest	NULL	2024-09-13 12:00:00

describe table dev.default.bridges;
col_name	data_type	comment
country             	string              	                    
city                	string              	                    
bridges             	struct<length:bigint,name:string>	                    
_time               	timestamp   
```
So the values in the column `bridges` are always `null`, and the column type is `struct<length:bigint,name:string>`. Furthermore, it is impossible to reference any values in column `bridges` via expressions like `bridges[0].name`, e.g.
```sql
select bridges[0].name from dev.default.bridges;
line 1:7 no viable alternative at input 'select bridges'
[INVALID_EXTRACT_FIELD_TYPE] Field name should be a non-null string literal, but it's "0".
```

On the other hand, when I load the same data via PySpatk e.g.
```python
df_bridges = spark.read.option("multiline","true").json('/home/lukasz/projects/aws/bridges.json')
df_bridges..write.saveAsTable("city_bridge")
```

Then problems related to `bridges` column do not occur, e.g
```sql
select * from city_bridge;
_time	bridges	city	country
2024-09-13T12:00:00	[{"length":801,"name":"Tower Bridge"},{"length":928,"name":"London Bridge"}]	London	England
2024-09-13T12:00:00	[{"length":232,"name":"Pont Neuf"},{"length":160,"name":"Pont Alexandre III"}]	Paris	France
2024-09-13T12:00:00	[{"length":48,"name":"Rialto Bridge"},{"length":11,"name":"Bridge of Sighs"}]	Venice	Italy
2024-09-13T12:00:00	[{"length":516,"name":"Charles Bridge"},{"length":343,"name":"Legion Bridge"}]	Prague	Czech Republic
2024-09-13T12:00:00	[{"length":375,"name":"Chain Bridge"},{"length":333,"name":"Liberty Bridge"}]	Budapest	Hungary
Time taken: 0.304 seconds, Fetched 5 row(s)


spark-sql (default)> describe table city_bridge;
line 1:15 extraneous input 'city_bridge' expecting <EOF>
24/10/10 14:00:18 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
col_name	data_type	comment
_time               	string              	                    
bridges             	array<struct<length:bigint,name:string>>	                    
city                	string              	                    
country             	string              	                    
Time taken: 0.215 seconds, Fetched 4 row(s)


spark-sql (default)> select bridges[0].name from city_bridge;
line 1:7 no viable alternative at input 'select bridges'
bridges[0].name
Tower Bridge
Pont Neuf
Rialto Bridge
Charles Bridge
Chain Bridge
Time taken: 0.114 seconds, Fetched 5 row(s)
spark-sql (default)> select bridges.name from city_bridge;
line 1:7 no viable alternative at input 'select bridges'

```

In the above case, the `bridges` column type is `array<struct<length:bigint,name:string>>`, and it is possible to select values from the column. Therefore, I think the future implementation of the `flatten` command may not work correctly with data loaded from OpenSearch.

**Comment by lukasz-soszynski-eliatra** [comment]
I have a question related to the implementation details of the `flatten` command. Nested JSON objects are represented in Spark by two data types
- Struct
- Arrays

Furthermore, the `flatten` command should work correctly with both types. It is relatively simple to flatten Struct. For example, to flatten the `coor` object from the below document, it is enough to use `*` operator (`select coor.*from table1`)
```json
{
    "_time": "2024-09-13T12:00:00",
    "bridges": [
      {"name": "Rialto Bridge", "length": 48},
      {"name": "Bridge of Sighs", "length": 11}
    ],
    "city": "Venice",
    "country": "Italy",
    "coor": {
      "lat": 45.4408,
      "long": 12.3155,
      "alt": 2
    }
  }
```
On the other hand, flattening arrays requires the usage of [generator functions](https://spark.apache.org/docs/latest/sql-ref-functions-builtin.html#generator-functions), that is, functions that create new rows. Unfortunately, usage of the generator function is related to quite severe restrictions:
- generator function can't be used together with `case`, `if`, etc. functions
- only one generator function can appear in the select clause
- etc.

Therefore, it is impossible to implement a condition that depends on the field type to use a generator function to flatten arrays or  `*` operator to flatten `struct`.

Avoiding using condition functions together with generator functions like in the below example also results in type-related validation error (`null` of type `array` cannot be cast to a `struct`)
```sql
select inline_outer(array), struct.* 
from (
    select 
        if(startswith(typeof(bridges), 'array'), bridges, null) as array, 
        if(startswith(typeof(bridges), 'struct'), bridges, null) as struct 
    from table1 c);

line 1:7 no viable alternative at input 'select inline_outer'
Can only star expand struct data types. Attribute: `ArrayBuffer(struct)`.; line 1 pos 28
```

The approach also has another disadvantage. It is impossible to manipulate the names of flattened columns freely.

To solve the problems described above, we can use two approaches.

1. Change the `flatten` command syntax, e.g. 
```sql
... flatten array my_field_with_aray 
| flatten struct my_field_with_struct
```
However, this solution will contain cons for freely manipulating flattened column names.

2. Another option is to implement a custom generator function that uses `org.apache.spark.sql.catalyst.expressions.GeneratorOuter` or `org.apache.spark.sql.catalyst.expressions.ExplodeBase` as the supper class. However, this requires some additional investigation and, therefore, might be more expensive.

@YANG-DB Could you please tell me what are your preference and how we should implement the `flatten` command?

**Comment by lukasz-soszynski-eliatra** [comment]
Currently, I am using the below JSON file to test my implementation
```json
[{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Tower Bridge","length":801},{"name":"London Bridge","length":928}],"city":"London","country":"England","coor":{"lat":51.5074,"long":-0.1278,"alt":35}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Pont Neuf","length":232},{"name":"Pont Alexandre III","length":160}],"city":"Paris","country":"France","coor":{"lat":48.8566,"long":2.3522,"alt":35}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Rialto Bridge","length":48},{"name":"Bridge of Sighs","length":11}],"city":"Venice","country":"Italy","coor":{"lat":45.4408,"long":12.3155,"alt":2}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Charles Bridge","length":516},{"name":"Legion Bridge","length":343}],"city":"Prague","country":"Czech Republic","coor":{"lat":50.0755,"long":14.4378,"alt":200}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Chain Bridge","length":375},{"name":"Liberty Bridge","length":333}],"city":"Budapest","country":"Hungary","coor":{"lat":47.4979,"long":19.0402,"alt":96}},{"_time":"1990-09-13T12:00:00","bridges":null,"city":"Warsaw","country":"Poland","coor":null}]
```

The file is loaded using PySpark and the following commands
```python
df_coor = spark.read.option("multiline","true").json('/home/lukasz/projects/aws/bridges_coordinates.json')
df_coor.write.saveAsTable("bridges_coor")
```


I can use the following SQL statement to load data in integration tests.
```sql
CREATE TEMPORARY VIEW bridges_coor
USING org.apache.spark.sql.json
OPTIONS (
  path "/home/lukasz/projects/aws/bridges_coordinates.json",
  multiLine true
);
```

@YANG-DB Is this testing method appropriate from your point of view, or do you have other recommendations (S3 tables)?

**Comment by YANG-DB** [comment]
> I have a question related to the implementation details of the `flatten` command. Nested JSON objects are represented in Spark by two data types
> 
> * Struct
> * Arrays
> 
> Furthermore, the `flatten` command should work correctly with both types. It is relatively simple to flatten Struct. For example, to flatten the `coor` object from the below document, it is enough to use `*` operator (`select coor.*from table1`)
> 
> ```json
> {
>     "_time": "2024-09-13T12:00:00",
>     "bridges": [
>       {"name": "Rialto Bridge", "length": 48},
>       {"name": "Bridge of Sighs", "length": 11}
>     ],
>     "city": "Venice",
>     "country": "Italy",
>     "coor": {
>       "lat": 45.4408,
>       "long": 12.3155,
>       "alt": 2
>     }
>   }
> ```
> 
> On the other hand, flattening arrays requires the usage of [generator functions](https://spark.apache.org/docs/latest/sql-ref-functions-builtin.html#generator-functions), that is, functions that create new rows. Unfortunately, usage of the generator function is related to quite severe restrictions:
> 
> * generator function can't be used together with `case`, `if`, etc. functions
> * only one generator function can appear in the select clause
> * etc.
> 
> Therefore, it is impossible to implement a condition that depends on the field type to use a generator function to flatten arrays or `*` operator to flatten `struct`.
> 
> Avoiding using condition functions together with generator functions like in the below example also results in type-related validation error (`null` of type `array` cannot be cast to a `struct`)
> 
> ```sql
> select inline_outer(array), struct.* 
> from (
>     select 
>         if(startswith(typeof(bridges), 'array'), bridges, null) as array, 
>         if(startswith(typeof(bridges), 'struct'), bridges, null) as struct 
>     from table1 c);
> 
> line 1:7 no viable alternative at input 'select inline_outer'
> Can only star expand struct data types. Attribute: `ArrayBuffer(struct)`.; line 1 pos 28
> ```
> 
> The approach also has another disadvantage. It is impossible to manipulate the names of flattened columns freely.
> 
> To solve the problems described above, we can use two approaches.
> 
> 1. Change the `flatten` command syntax, e.g.
> 
> ```sql
> ... flatten array my_field_with_aray 
> | flatten struct my_field_with_struct
> ```
> 
> However, this solution will contain cons for freely manipulating flattened column names.
> 
> 2. Another option is to implement a custom generator function that uses `org.apache.spark.sql.catalyst.expressions.GeneratorOuter` or `org.apache.spark.sql.catalyst.expressions.ExplodeBase` as the supper class. However, this requires some additional investigation and, therefore, might be more expensive.
> 
> @YANG-DB Could you please tell me what are your preference and how we should implement the `flatten` command?

@lukasz-soszynski-eliatra Thanks for the analysis - IMO separating `flatten` into 2 unique use cases make sense:
```
... flatten array my_field_with_aray 
| flatten struct my_field_with_struct
```
@LantaoJin @penghuo WDYT ?

**Comment by YANG-DB** [comment]
> Currently, I am using the below JSON file to test my implementation
> 
> ```json
> [{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Tower Bridge","length":801},{"name":"London Bridge","length":928}],"city":"London","country":"England","coor":{"lat":51.5074,"long":-0.1278,"alt":35}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Pont Neuf","length":232},{"name":"Pont Alexandre III","length":160}],"city":"Paris","country":"France","coor":{"lat":48.8566,"long":2.3522,"alt":35}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Rialto Bridge","length":48},{"name":"Bridge of Sighs","length":11}],"city":"Venice","country":"Italy","coor":{"lat":45.4408,"long":12.3155,"alt":2}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Charles Bridge","length":516},{"name":"Legion Bridge","length":343}],"city":"Prague","country":"Czech Republic","coor":{"lat":50.0755,"long":14.4378,"alt":200}},{"_time":"2024-09-13T12:00:00","bridges":[{"name":"Chain Bridge","length":375},{"name":"Liberty Bridge","length":333}],"city":"Budapest","country":"Hungary","coor":{"lat":47.4979,"long":19.0402,"alt":96}},{"_time":"1990-09-13T12:00:00","bridges":null,"city":"Warsaw","country":"Poland","coor":null}]
> ```
> 
> The file is loaded using PySpark and the following commands
> 
> ```python
> df_coor = spark.read.option("multiline","true").json('/home/lukasz/projects/aws/bridges_coordinates.json')
> df_coor.write.saveAsTable("bridges_coor")
> ```
> 
> I can use the following SQL statement to load data in integration tests.
> 
> ```sql
> CREATE TEMPORARY VIEW bridges_coor
> USING org.apache.spark.sql.json
> OPTIONS (
>   path "/home/lukasz/projects/aws/bridges_coordinates.json",
>   multiLine true
> );
> ```
> 
> @YANG-DB Is this testing method appropriate from your point of view, or do you have other recommendations (S3 tables)?

regarding the test method - lets try to use a more generic way ? 
@LantaoJin - any suggestions ?

**Comment by YANG-DB** [comment]
@salyh @lukasz-soszynski-eliatra please review #780 to get a few ideas

**Comment by YANG-DB** [comment]
> @YANG-DB Many thanks for your suggestions related to testing. Syntax extension to the `flatten` command might not be required. [The current implementation](https://github.com/opensearch-project/opensearch-spark/pull/784) of the command works correctly with
> 
> * structs
> * arrays of structs
> * also, maps should be supported, although I did not test this.
> 
> The implementation in the current shape does not support arrays with simple types like `[0,1,2,3]`
> 
> Here are some examples of the `flatten` command.
> 
> The table `coor` below contains two interesting columns:
> 
> * `bridges` - `array<struct<length:bigint,name:string>>`
> * `color` - `struct<alt:bigint,lat:double,long:double>`
> 
> ```
> +-------------------+--------------------+--------+--------------------+--------------+
> |              _time|             bridges|    city|                coor|       country|
> +-------------------+--------------------+--------+--------------------+--------------+
> |2024-09-13T12:00:00|[{801, Tower Brid...|  London|{35, 51.5074, -0....|       England|
> |2024-09-13T12:00:00|[{232, Pont Neuf}...|   Paris|{35, 48.8566, 2.3...|        France|
> |2024-09-13T12:00:00|[{48, Rialto Brid...|  Venice|{2, 45.4408, 12.3...|         Italy|
> |2024-09-13T12:00:00|[{516, Charles Br...|  Prague|{200, 50.0755, 14...|Czech Republic|
> |2024-09-13T12:00:00|[{375, Chain Brid...|Budapest|{96, 47.4979, 19....|       Hungary|
> |1990-09-13T12:00:00|                NULL|  Warsaw|                NULL|        Poland|
> +-------------------+--------------------+--------+--------------------+--------------+
> ```
> 
> The columns `bridges` and `coor` can be flattened in the following way
> 
> ```sql
> source=coor | flatten bridges | flatten coor;
> ```
> 
> The result of the above command is
> 
> ```
> _time	city	country	length	name	alt	lat	long
> 2024-09-13T12:00:00	London	England	801	Tower Bridge	35	51.5074	-0.1278
> 2024-09-13T12:00:00	London	England	928	London Bridge	35	51.5074	-0.1278
> 2024-09-13T12:00:00	Paris	France	232	Pont Neuf	35	48.8566	2.3522
> 2024-09-13T12:00:00	Paris	France	160	Pont Alexandre III	35	48.8566	2.3522
> 2024-09-13T12:00:00	Venice	Italy	48	Rialto Bridge	2	45.4408	12.3155
> 2024-09-13T12:00:00	Venice	Italy	11	Bridge of Sighs	2	45.4408	12.3155
> 2024-09-13T12:00:00	Prague	Czech Republic	516	Charles Bridge	200	50.0755	14.4378
> 2024-09-13T12:00:00	Prague	Czech Republic	343	Legion Bridge	200	50.0755	14.4378
> 2024-09-13T12:00:00	Budapest	Hungary	375	Chain Bridge	96	47.4979	19.0402
> 2024-09-13T12:00:00	Budapest	Hungary	333	Liberty Bridge	96	47.4979	19.0402
> 1990-09-13T12:00:00	Warsaw	Poland	NULL	NULL	NULL	NULL	NULL
> Time taken: 0.169 seconds, Fetched 11 row(s)
> ```
> 
> Please remember that the above result contains additional rows created when the array `bridges` is flattened.

@lukasz-soszynski-eliatra ok - lets complete this PR and figure out the simple type array support afterwards - maybe in a different syntax ?

**Comment by lukasz-soszynski-eliatra** [comment]
Supporting arrays of simple types should be trivial if a dedicated syntax is used. However, it might still be possible to support such arrays with the current syntax, but such an approach is probably a bit more challenging. Anyway, I will not include support for such arrays in the current PR.

**Comment by lukasz-soszynski-eliatra** [comment]
> also, maps should be supported, although I did not test this.

Unfortunately, after tests, it turns out maps are also unsupported.
