### ISSUE TITLE
[FEATURE] Add "between" expression to PPL

### ISSUE THREAD

**Issue by A-Gray-Cat** [opensearch-project/opensearch-spark#679]
**Is your feature request related to a problem?**
When doing comparisons for a range, it will be very convenient to have a between command, e.g.

Instead of writing, `... | where datetime >= '2024-09-10' and datetime <= '2024-09-15'`, it can be written as `... | where datetime between '2024-09-10' and '2024-09-15'`.

**What solution would you like?**
Add the "between" expression. This is a nice to have.

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by YANG-DB** [comment]
@salyh Can u plz review and validate this issue ?
thanks

**Comment by salyh** [comment]
It's a valid request albeit its only syntactic sugar. Spark SQL does have a BETWEEN function so it makes sense.

@A-Gray-Cat  @YANG-DB I suggest to implement it like `expr1 [NOT] BETWEEN expr2 AND expr3 - evaluate if expr1 is [not] in between expr2 and expr3.` exactly like Spark SQL is implementing it (https://spark.apache.org/docs/latest/api/sql/#between)

**Comment by dblock** [comment]
[Catch All [Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta),  [3](https://github.com/krisfreedain),  [4](https://github.com/lukas-vlcek/)]

**Comment by YANG-DB** [comment]
> It's a valid request albeit its only syntactic sugar. Spark SQL does have a BETWEEN function so it makes sense.
> 
> @A-Gray-Cat @YANG-DB I suggest to implement it like `expr1 [NOT] BETWEEN expr2 AND expr3 - evaluate if expr1 is [not] in between expr2 and expr3.` exactly like Spark SQL is implementing it (https://spark.apache.org/docs/latest/api/sql/#between)

@salyh agree lets proceed with the suggested syntax
