### ISSUE TITLE
[FEATURE] Several date and time functions are missing from Spark based PPL driver

### ISSUE THREAD

**Issue by A-Gray-Cat** [opensearch-project/opensearch-spark#722]
**Is your feature request related to a problem?**
1. DATE_SUB() function is missing from Spark based PPL driver.
2. NOW() function is missing.

Both would return the following error:
```
{"Message":"Fail to run query. Cause: Not Supported operation : Function"}

```

**What solution would you like?**
Bring both functions to Spark based PPL driver:
- https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/functions/datetime.rst#id43
- https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/functions/datetime.rst#date-sub

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by YANG-DB** [comment]
Adding additional context here:

The following query needs to be supported:
```sql
source = http_logs | eval c1 = unix_timestamp(@timestamp) | eval c2 = now() | eval c3 = 
  DAY_OF_WEEK(@timestamp) | eval c4 = 
  DAY_OF_MONTH(@timestamp) | eval c5 = 
  DAY_OF_YEAR(@timestamp) | eval c6 = 
  WEEK_OF_YEAR(@timestamp) | eval c7 = 
  WEEK(@timestamp) | eval c8 = 
  MONTH_OF_YEAR(@timestamp) | eval c9 = 
  HOUR_OF_DAY(@timestamp) | eval c10 = 
  MINUTE_OF_HOUR(@timestamp) | eval c11 = 
  SECOND_OF_MINUTE(@timestamp) | eval c12 =
  LOCALTIME() | fields c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12 | head 10
```

[Here are the specifications](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/functions/conversion.rst)

**Comment by A-Gray-Cat** [comment]
and please don't forget `NOW()` and `DATE_SUB` 😄

**Comment by salyh** [comment]
On the main branch I can successfully execute:

`scala>  val dfp = spark.sql("source = dev.default.iot | eval @timestamp = now() | eval c1 = unix_timestamp(@timestamp) | eval c2 = now() | eval c3 = DAY_OF_WEEK(@timestamp) | eval c4 = DAY_OF_MONTH(@timestamp) | eval c5 = DAY_OF_YEAR(@timestamp) | eval c6 = WEEK_OF_YEAR(@timestamp) | eval c7 = WEEK(@timestamp) | eval c8 = MONTH_OF_YEAR(@timestamp) | eval c9 = HOUR_OF_DAY(@timestamp) | eval c10 =  MINUTE_OF_HOUR(@timestamp) | eval c11 = SECOND_OF_MINUTE(@timestamp) | eval c12 =LOCALTIME() | fields c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12 | head 10"); dfp.show()`

```
+----------+--------------------+---+---+---+---+---+---+---+---+---+--------------------+
|        c1|                  c2| c3| c4| c5| c6| c7| c8| c9|c10|c11|                 c12|
+----------+--------------------+---+---+---+---+---+---+---+---+---+--------------------+
|1728485509|2024-10-09 16:51:...|  4|  9|283| 41| 41| 10| 16| 51| 49|2024-10-09 16:51:...|
|1728485509|2024-10-09 16:51:...|  4|  9|283| 41| 41| 10| 16| 51| 49|2024-10-09 16:51:...|
|1728485509|2024-10-09 16:51:...|  4|  9|283| 41| 41| 10| 16| 51| 49|2024-10-09 16:51:...|
|1728485509|2024-10-09 16:51:...|  4|  9|283| 41| 41| 10| 16| 51| 49|2024-10-09 16:51:...|
|1728485509|2024-10-09 16:51:...|  4|  9|283| 41| 41| 10| 16| 51| 49|2024-10-09 16:51:...|
+----------+--------------------+---+---+---+---+---+---+---+---+---+--------------------+

```

So it seems all function mentioned in https://github.com/opensearch-project/opensearch-spark/issues/722#issuecomment-2394358931 and `now()` are working already.

**Comment by salyh** [comment]
DATE_SUB is also working, the syntax is `date_sub(start_date, num_days) - Returns the date that is num_days before start_date.` https://spark.apache.org/docs/3.5.1/api/sql/index.html#date_sub

```

scala>  val dfp = spark.sql("source=dev.default.iot | eval a = DATE_SUB(DATE('2008-01-02'), 31)");dfp.show()
+-----------+---------+--------------------+----------+
|temperature|device-id|           timestamp|         a|
+-----------+---------+--------------------+----------+
|         12|     1492|2023-04-06 17:07:...|2007-12-02|
|         12|     1492|2023-04-06 17:07:...|2007-12-02|
|         13|      256|2023-04-06 17:07:...|2007-12-02|
|         14|      257|2023-04-06 17:07:...|2007-12-02|
|         15|      258|2023-04-06 17:07:...|2007-12-02|
+-----------+---------+--------------------+----------+
```

**Comment by A-Gray-Cat** [comment]
Hello @salyh, thanks for the update. I suspect it's the version I'm testing with doesn't have these functions available. In addition, could you check if the `time()` function is also available? To run queries that fall within a specific time, it would require using the `time()` function. E.g. `... | where time_dt > TIME('2024-10-09').

Thanks.

**Comment by A-Gray-Cat** [comment]
And is this README up to date? https://github.com/opensearch-project/opensearch-spark/blob/fd3f82fc16273d47f17aa47e699aeaa8b4c3679d/ppl-spark-integration/README.md?plain=1#L258

**Comment by salyh** [comment]
> Hello @salyh, thanks for the update. I suspect it's the version I'm testing with doesn't have these functions available. In addition, could you check if the `time()` function is also available? To run queries that fall within a specific time, it would require using the `time()` function. E.g. `... | where time_dt > TIME('2024-10-09')`.
> 
> Thanks.

`time()` is not supported but `timestamp()`

scala>  val dfp = spark.sql("source=dev.default.iot | eval time = timestamp('2015-03-05T09:32:05.359')");dfp.show()

**Comment by A-Gray-Cat** [comment]
That's good to know. Thanks! I also noticed the syntax of the date_sub function is different from how it's documented here: https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/functions/datetime.rst#date-sub

**Comment by A-Gray-Cat** [comment]
Can we make sure that the syntax for the same function will be the same across non-spark based and spark based PPL?

**Comment by kenrickyap** [comment]
will start development on this ticket

**Comment by kenrickyap** [comment]
Hi @YANG-DB, just wanted to clarify the intention of this ticket. Is the intention of this ticket to:
1. Ensure that all datetime PPL functions implemented in opensearch-sql is also implemented in opensearch-spark
2. Ensure that all implemented datetime function in opensearch-spark have consistent syntax to the opensearch-sql counterpart.
Thanks!

**Comment by kenrickyap** [comment]
From investigation the following functions are currently unsupported in spark:
- addtime
- convert_tz
- current_time
- curtime
- datetime
- dayname
- from_days
- makedate
- maketime
- microsecond
- minute_of_day
- monthname
- period_add
- period_diff
- sec_to_time
- str_to_date
- subtime
- sysdate
- time
- time_format
- time_to_sec
- timediff
- to_days
- to_seconds
- utc_time
- utc_timestamp
- yearweek

Other observations
- date_format - most documented specifiers do not work.
- INTERVAL keyword does not work
- could not get extract query to work
- get_format params not recognized
- timestampdiff is unable to accept INTERVAL for first arg

**Comment by brijos** [comment]
There is a list of date/time functions which need to be implemented, but the following are high priority:


DATE_SUB() 
NOW()

If we see other bugs such as the ones defined in other observations, then we should address those as well.

**Comment by salyh** [comment]
@brijos see https://github.com/opensearch-project/opensearch-spark/issues/722#issuecomment-2402590941 and https://github.com/opensearch-project/opensearch-spark/issues/722#issuecomment-2402600231

**Comment by LantaoJin** [comment]
> DATE_SUB()

We have `subdate(date, days)` and `adddate(date, days)`. I will submit PRs to add `add_date(date, INTERVAL expr unit)` and `date_sub(date, INTERVAL expr unit)`

> NOW()

This function is present. Please check again. @brijos

**Comment by LantaoJin** [comment]
| functions | status | notes |
|-----------|--------|-------|
| addtime | missing | Spark does not support time datatype |
| convert_tz | missing | - |
| current_time | missing | Spark does not support time datatype |
| curtime | missing | Spark does not support time datatype |
| datetime | missing | P3 |
| dayname | missing | Spark 4.0.0+ |
| from_days | missing | P3 |
| makedate | missing | P3 |
| maketime | missing | Spark does not support time datatype; P3 |
| microsecond | missing | P3 |
| minute_of_day | missing | P3 |
| monthname | missing | Spark 4.0.0+ |
| period_add | missing | P3 |
| period_diff | missing | P3 |
| sec_to_time | missing | Spark 4.0.0+; P3 |
| str_to_date | missing | P3; use DATE_FORMAT as alternative |
| subtime | missing | P0; will fix it |
| sysdate | is present | - |
| time | missing | Spark does not support time datatype |
| time_format | missing | Spark does not support time datatype |
| time_to_sec | missing | Spark does not support time datatype |
| timediff | missing | Spark does not support time datatype |
| to_days | missing | P3 |
| to_seconds | missing | P3 |
| utc_time | missing | Spark does not support time datatype; P3 |
| utc_timestamp | missing | P3; use timestamp(now()) as alternative |
| yearweek | missing | P3 |
| extract | missing | P3 |
| get_format | missing | P3 |
| timestampdiff  | missing | P3 |

---
| question | answer |
|-----------|--------|
| date_format - most documented specifiers do not work. | Ref the new doc of [date_format](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/functions/ppl-datetime.md#date_format) |
| INTERVAL keyword does not work | will add it in the implementation of subtime() |
| could not get extract query to work | check above table | 
| get_format params not recognized | check above table | 
| timestampdiff is unable to accept INTERVAL for first arg | check above table | 

cc @anasalkouz

**Comment by A-Gray-Cat** [comment]
Sorry about the confusion @LantaoJin. The original comment suggested `date_sub` already worked, but we realized it didn't work in the spark ppl we were using for testing. I tried `subdate` command you suggested, and it works as expected with the `now()` command.
