### ISSUE TITLE
[BUG][SanityTest] Describe command doesn't work as expected on Glue catalog

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/opensearch-spark#738]
**What is the bug?**
`describe` command doesn't work as expected Glue catalog

**How can one reproduce the bug?**
1. Go to Workbench page. For example https://search-flint05-sanity-h5if7yelmxws5hc35cap2lauf4.us-east-1.es-integ.amazonaws.com/_dashboards/app/opensearch-query-workbench#/
2. Execute a PPL query `describe myglue_test.default.http_logs`
You will get error `[SCHEMA_NOT_FOUND] The schema `myglue_test` cannot be found.`

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by dblock** [comment]
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/reta)]
