### ISSUE TITLE
[BUG][SanityTest] stats `by` a high cardinality field will cause writing job fail with "size exceed limitation"

### ISSUE THREAD

**Issue by LantaoJin** [opensearch-project/opensearch-spark#740]
**What is the bug?**
When group by a high cardinality field, such as `clientip`, the spark writing job will fail "Request size exceeded 10485760 bytes" .

<img width="1634" alt="Screenshot 2024-10-01 at 17 33 09" src="https://github.com/user-attachments/assets/d15cd8c1-1f88-4a5a-868d-191c60005e11">
<img width="1651" alt="Screenshot 2024-10-01 at 15 12 07" src="https://github.com/user-attachments/assets/427b89c4-8d25-4c0d-bf53-183a630b70c4">

**How can one reproduce the bug?**
1. Go to Workbench page. For example https://search-flint05-sanity-h5if7yelmxws5hc35cap2lauf4.us-east-1.es-integ.amazonaws.com/_dashboards/app/opensearch-query-workbench#/
2. Execute a PPL query `source = myglue_test.default.http_logs | stats avg(size) by clientip`
3. Open the EMR-S job in Spark UI.

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by YANG-DB** [comment]
@LantaoJin what do you suggest here ? 
should we rewrite the query in such high carnality cases ?

**Comment by YANG-DB** [comment]
[fieldsummary](https://github.com/opensearch-project/opensearch-spark/issues/662) should provide statistical info about fields and assisting the cost estimation of the query including cardinality
