### ISSUE TITLE
[FEATURE] PPL Add Cryptographic hash function in eval and where command

### ISSUE THREAD

**Issue by Gokul-Radhakrishnan** [opensearch-project/opensearch-spark#759]
**Is your feature request related to a problem?**
Currently there is no support for Cryptographic hash function like sha512  in eval and where command

**What solution would you like?**
Need to implement the Cyptographic hash function

**Do you have any additional context?**
Refer [Splunk Cryptographic function](https://docs.splunk.com/Documentation/SCS/current/SearchReference/CryptographicFunctions)

**Comment by YANG-DB** [comment]
@Gokul-Radhakrishnan thanks again for your contributions !!

**Comment by LantaoJin** [comment]
Does anybody know why the PR includes `SHA2`?
https://github.com/opensearch-project/opensearch-spark/pull/788/files#diff-14f05cc06d603f85317459cb01a0cc08cbf018bd7b746ae377d967aa5fa1f719R627-R631

The link of Splunk doc in description did not mention it at all.

**Comment by Gokul-Radhakrishnan** [comment]
@LantaoJin 
It has sha256 and sha512 functions from SHA-2 family 

<img width="882" alt="Image" src="https://github.com/user-attachments/assets/0a938511-2a85-4223-ac8f-3eb7c8ee9b4b" />
