### ISSUE TITLE
[FEATURE] Fail long waiting statement

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#80]
when spark job pick up the statement, if the statement in waiting state longer than 10 minutes compare to submitTime, spark job should put the state to FAIL and error = timeout.

**Comment by kaituo** [comment]
I am using spark.sparkContext.cancelJobGroup(flintCommand.queryId) to cancel query.

**Comment by kaituo** [comment]
already implemented in above PR.
