### ISSUE TITLE
[BUG] REPL Job should return meaning full error message.

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#83]
**What is the bug?**
* submit query with syntax error.
```
select * from mys3.default.http_logs limit1 1"
```
* query response
```
{
  "status": "FAILED",
  "error": "command fail: org.opensearch.flint.app.FlintCommand@1f13eabb"
}
```
* expected
```
Syntax error at or near '1': extra input '1'(line 1, pos 44)

== SQL ==
select * from mys3.default.http_logs limit1 1
--------------------------------------------^^^
```

**Comment by kaituo** [comment]
Fixed the issue. 

Result index:

{
        "_index": "query_results2",
        "_id": "YbDlTosBXV3LmSNnpu0b",
        "_score": 6.3868794,
        "_source": {
          "jobRunId": "00fe4afa2ogur80q",
          "applicationId": "00fd775baqpu4g0p",
          "dataSourceName": "myS3Glue",
          "status": "FAILED",
          "error": """Syntax error: 
Syntax error at or near '1': extra input '1'(line 1, pos 39)

== SQL ==
select * from default.http_logs limit1 1
---------------------------------------^^^
""",
          "queryId": "100",
          "queryText": "select * from default.http_logs limit1 1",
          "sessionId": "10",
          "updateTime": 1697835751264
        }
      }

Session index:
{
        "_index": "query_results2",
        "_id": "_L8DT4sBIPWmei_EaWXt",
        "_score": 6.2766433,
        "_source": {
          "jobRunId": "00fe4b1tf3s1580q",
          "applicationId": "00fd775baqpu4g0p",
          "dataSourceName": "myS3Glue",
          "status": "FAILED",
          "error": """Syntax error: 
Syntax error at or near '1': extra input '1'(line 1, pos 39)

== SQL ==
select * from default.http_logs limit1 1
---------------------------------------^^^
""",
          "queryId": "100",
          "queryText": "select * from default.http_logs limit1 1",
          "sessionId": "10",
          "updateTime": 1697837701785
        }
      }
