### ISSUE TITLE
[FEATURE]Reduce IT Test time

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/opensearch-spark#853]
**Is your feature request related to a problem?**

Currently it takes more than 60 minutes to complete the tests for the [ test & build github workflow ](https://github.com/opensearch-project/opensearch-spark/blob/main/.github/workflows/test-and-build-workflow.yml)

**What solution would you like?**
We need to significantly reduce this time for better development responsiveness and fail-fast

**Do you have any additional context?**
- attempt to parallel the IT tests

**Comment by andrross** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/krisfreedain), [5](https://github.com/amistrn)]
