### ISSUE TITLE
[BUG] Show covering index runs into error when index is not present

### ISSUE THREAD

**Issue by ps48** [opensearch-project/opensearch-spark#86]
**What is the bug?**
Show covering index runs into error when index is not present.  
`{"data":{"ok":true,"resp":{"status":"FAILED","error":"Fail to run query or write result"}}}` 

**How can one reproduce the bug?**
1. Make sure a covering index is not present in table  ex.`alb_logs`. 
2. Run `SHOW INDEX ON myS3.default.alb_logs` 

**What is the expected behavior?**
This should return success with empty `[]` response. 
Error/Failed state should only be sent when query execution runs into error.

**Comment by dai-chen** [comment]
It should be fixed in https://github.com/opensearch-project/opensearch-spark/pull/81. Please verify latest artifact and let me know if still have issue. Thanks!

**Comment by dai-chen** [comment]
Feel free to reopen if any problem. Thanks!
