### ISSUE TITLE
[FEATURE] Incremental refresh index on Hive source table

### ISSUE THREAD

**Issue by dai-chen** [opensearch-project/opensearch-spark#91]
**Is your feature request related to a problem?**

Currently Spark structured streaming only supports Spark Data Source table. For Hive table, it throws exception when starting streaming job.

**What solution would you like?**

Opt-1: Support streaming on Hive table either enhance stream source operator or convert Hive table internally (not sure if possible)
Opt-2: Give user clear message simply or how to create Spark DS table guide upon error. Related to https://github.com/opensearch-project/opensearch-spark/issues/65

**Comment by dai-chen** [comment]
A new option is this may be supported by Lazy Build idea in https://github.com/opensearch-project/opensearch-spark/issues/118 if the proposal feasible.

**Comment by dai-chen** [comment]
Need to double check if all or only certain Hive table cannot be supported by Spark structured streaming.

**Comment by penghuo** [comment]
no plan to support hive table as streaming source in short term. more context of hive table issue with spark structured streaming query in https://github.com/opensearch-project/opensearch-spark/issues/65#issuecomment-1908974123.
