### ISSUE TITLE
[FEATURE] Metrics Requirements - REPL

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/opensearch-spark#96]
* Statement executionTime
  * opt-1 REPL update lastUpdateTime field of statement doc when ever update statement state.  client calculate executionTime =  lastUpdateTime - submitTime.
  * opt-2 REPL update executionTime.

**Comment by kaituo** [comment]
Implemented opt-2. In result doc, we have queryRunTime in milliseconds.

{
        "_index": "query_results2",
        "_id": "de1Xp4sB3TUuWZmbQ6Gy",
        "_score": null,
        "_source": {
          "jobRunId": "00fei4lh5a82280q",
          "applicationId": "00fd777k3k3ls20p",
          "dataSourceName": "myS3Glue",
          "status": "FAILED",
          "error": "Executing SELECT AVG(size) FROM my_glue1.default.http_logs_150 WHERE status = 403  timed out",
          "queryId": "101",
          "queryText": "SELECT AVG(size) FROM my_glue1.default.http_logs_150 WHERE status = 403 ",
          "sessionId": "10",
          "updateTime": 1699319594764,
          "queryRunTime": 60002
        }
